[package]
name = "nuko"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"
description = "Future static site generator"
license = "MIT"

[dependencies]
atty = "0.2.14"
anyhow = "1.0.32"
clap = "2.33.2"
lazy_static = "1.4.0"
thiserror = "1.0.20"

[[bin]]
name = "nuko"
