[package]
name = "nuko-org-parser"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
fancy-regex = "0.3"
regex = "1.3.9"
serde = "1"
serde_derive = "1"
smol_str = { version = "0.1", features = ["serde"] }
thiserror = "1.0"
