[package]
name = "nuko-org-parser"
version = "0.1.0"
authors = ["Mats A. <mats@mats.sh>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
lazy_static = "1.4"
fancy-regex = "0.3"
smol_str = "0.1"
thiserror = "1.0"
